branches:
  except:
    - gh-pages
sudo: false
language: perl6
perl6: latest
before_install:
  - rm -rf /opt/pyenv
  - curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init - >/dev/null)"
  - PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.9
  - pyenv global 3.7.9
  - pyenv rehash
  - git clone https://github.com/ugexe/zef.git $HOME/zef
install:
  - perl6 -I $HOME/zef/lib $HOME/zef/bin/zef install . --debug
